import { yekan } from "@/utils/font";
import "./globals.css";

export const metadata = {
  title: "خرید و فروش ملک",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekan.className}>{children}</body>
    </html>
  );
}
